<?php
$headTitle = 'Main Page';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-xs-6">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
    <div class="col-xs-6">
        <ul class="list-inline pull-right app-login-register-block">
            <li><a href="/users/login">Login</a></li> |
            <li><a href="/users/register">Register</a></li>
        </ul>
    </div>
</div>