<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/app-script.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <ul class="nav navbar-nav">
                        <li class="<?php if (strip_tags($this->headTitle()) == 'Main Page') { echo 'active'; } ?>">
                            <a class="navbar-brand" href="<?php echo $this->url('users') ?>">Users</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?php if (strip_tags($this->headTitle()) == 'Time Page') { echo 'active'; } ?>">
                            <a href="<?php echo $this->url('current-time') ?>"><?php echo $this->translate('Current Time') ?></a>
                        </li>
                        <li class="<?php if (strip_tags($this->headTitle()) == 'Manage Users') { echo 'active'; } ?>">
                            <a href="<?php echo $this->url('users/management') ?>"><?php echo $this->translate('Manage Users') ?></a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div>
                <?php
                echo $this->navigation('navigation')
                          ->breadcrumbs()
                          ->setMinDepth(0)
                          ->setPartial('partial/breadcrumb.phtml', 'users');
                ?>
                <hr>
                <?php echo $this->content; ?>
            </div>
            <footer>
                <hr>
                <p>&copy; 2005 - <?php echo date('Y') ?> by PHP-User. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
